#!/usr/bin/gnuplot
set terminal svg size 800,600
set output "memory.svg"
set grid xtics ytics
set title "Memory Usage"
set xlabel "Time during test"
set ylabel "size (MB)"
set xdata time
set timefmt "%d-%m %H:%M:%S"
set format x "%M:%S"
plot "stat.stat" using 1:9 title "used" with lines, \
"stat.stat" using 1:10 title "buff" with lines, \
"stat.stat" using 1:11 title "cach" with lines, \
"stat.stat" using 1:12 title "free" with lines
