#!/bin/bash
SETINFO="$1"

source ./config
RESULTPSQL="psql -h $RESULTHOST -U $RESULTUSER -p $RESULTPORT -d $RESULTDB"

if [ -z "$SETINFO" ] ; then
  echo Usage:  $0 \"description\"
  echo Run without any parameters for help and to display existing sets
  echo
  $RESULTPSQL -c "SELECT info, testdb, testuser, testhost, testport FROM testset ORDER BY set"
  exit 1
fi

$RESULTPSQL -tAq -c "INSERT INTO testset(info, testdb, testuser, testhost, testport) VALUES('$SETINFO', '$TESTDB', '$TESTUSER', '$TESTHOST', '$TESTPORT') RETURNING set"
