#!/usr/bin/gnuplot
set terminal svg size 800,600
set datafile separator ","
set style data linespoints
set grid xtics ytics
set output "disk.svg"
set title "disk"
set xlabel "Time during test"
set ylabel "Disk Operations"
set xdata time
set timefmt "%s"
set format x "%M:%S"
plot "dstat.stat" using 1:18 title "disk reads" with linespoints linecolor rgb "blue", \
"dstat.stat" using 1:19 title "disk writes" with linespoints linecolor rgb "orange"
