#!/usr/bin/gnuplot
set terminal svg size 800,600
set datafile separator ","
set output "swap.svg"
set style data lines
set grid xtics ytics
set title "Swap Statistics"
set xlabel "Time during test"
set ylabel "Pages"
set yrange [0:]
set xdata time
set timefmt "%d-%m %H:%M:%S"
set format x "%M:%S"
plot "dstat.stat" using 1:12 title "Pages Used" with lines, \
"dstat.stat" using 1:13 title "Pages Free" with lines
