#!/usr/bin/gnuplot
set terminal svg size 800,600
set output "tps.svg"
set title "TPS"
set grid xtics mxtics ytics mytics
set xlabel "Time during test"
set ylabel "TPS"
set xdata time
set timefmt "%s"
plot "tpsdata.txt" using 1:2:(1.0) smooth acsplines with lines title "Interpolated TPS (Weighted spline, weight 1)" linecolor rgb "orange", \
"tpsdata.txt" using 1:2 with lines notitle linecolor rgb "red"
